### ISSUE TITLE
NotRegistered Error

### ISSUE THREAD

**Issue by Mohammad-Hany** [HoseanRC/shad-api#2]
Hello
I am using this package for the first time, when I insert my auth token and run my project, I get "shadapi.exceptions.NotRegistered:" error.

`from shadapi import Client

app = Client("******************************")

async def my_bot(bot):
    await bot.sendText('object_guid', '``Hello`` __from__ **Shad Api**!')

app.run(my_bot)`

Error:

`
(venv) C:\Users\MHany\Desktop\AdabBot>c:/Users/MHany/Desktop/AdabBot/venv/Scripts/python.exe c:/Users/MHany/Desktop/AdabBot/test.py
Traceback (most recent call last):
  File "c:\Users\MHany\Desktop\AdabBot\test.py", line 8, in <module>
    app.run(my_bot)
  File "c:\Users\MHany\Desktop\AdabBot\venv\Lib\site-packages\shadapi\accounts\_client.py", line 439, in run
    RUN(runner())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\MHany\Desktop\AdabBot\venv\Lib\site-packages\shadapi\accounts\_client.py", line 438, in runner       
    await func(methods)
  File "c:\Users\MHany\Desktop\AdabBot\test.py", line 6, in my_bot
    await bot.sendText('object_guid', '``Hello`` __from__ **Shad Api**!')
  File "c:\Users\MHany\Desktop\AdabBot\venv\Lib\site-packages\shadapi\accounts\methods\__init__.py", line 140, in sendText
    data = await self.make.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\MHany\Desktop\AdabBot\venv\Lib\site-packages\shadapi\accounts\methods\__init__.py", line 55, in request
    raise NotRegistered('Your AUTH is incorrect')
shadapi.exceptions.NotRegistered: Your AUTH is incorrect`

**Comment by HoseanRC** [comment]
this project is old, and i didn't think i would ever work on it again, but i might look into that

**Comment by Danger-Mkh** [comment]
The `api_version` change from `5` to `6`. also added new parameter `sign`

is there a way we could continue this project ?!
or alternate way ?!

**Comment by HoseanRC** [comment]
> The `api_version` change from `5` to `6`. also added new parameter `sign`
> 
> is there a way we could continue this project ?! or alternate way ?!

i checked the library a couple of days ago
i did find the `api_version` to be upgraded, but couldn't find the `sign` you're talking about
i will check if i could fix it.
i would probably create a real fork from the rubika repo tho since it did update and that it would be much easier to use that

**Comment by miaad-akbari** [comment]
@HoseanRC i have the same issue
